### ISSUE TITLE
Racket7 build failures

### ISSUE THREAD

**Issue by samth** [racket/racket#2090]
This issue tracks build failures of packages related to the upcoming racket version 7 release. Current status of all Racket packages is here: https://plt.eecs.northwestern.edu/pkg-build/

Test failures are tracked in #2099.

### Remaining errors:

- [ ] `racket-language-server`: Like `racket-langserver`, this uses `syntax/parse/experimental/template` and `??` in a `syntax` form. ~@rmculpepper, can you make a suggestion for fixing this?~  An identical fix to `racket-langserver` should work, issue at https://github.com/theia-ide/racket-language-server/issues/12.

The current error is:

```
who2: attribute contains non-syntax value
  value: #f
  in: who2
  compilation context...:
   /home/racket/build-pkgs/user/.racket/snapshot/pkgs/racket-language-server/protocol/json-util.rkt
   /home/racket/build-pkgs/user/.racket/snapshot/pkgs/racket-language-server/protocol/jsonrpc.rkt
   /home/racket/build-pkgs/user/.racket/snapshot/pkgs/racket-language-server/main.rkt
```

- [ ] `csrmesh`: Typed Racket error

Previously, Typed Racket had a bug that caused it not to type check portions of the code in this package. That bug was fixed shortly after 6.12 was released. However, the code in question was not ever type correct, and thus doesn't type check on 7.0

See https://gitlab.com/RayRacine/csrmesh/issues/1 for more details.

```
/home/racket/build-pkgs/user/.racket/snapshot/pkgs/csrmesh/csrmesh/packet.rkt:194:39: Type Checker: type mismatch
  expected: Word32
  given: Nonnegative-Integer
  in: sno
  location...:
   /home/racket/build-pkgs/user/.racket/snapshot/pkgs/csrmesh/csrmesh/packet.rkt:194:39
```

### pkg-build issues

- [x] `lang`, `zaoquil`: the repositories were deleted (That they are still listed as working for the regular pkg-build seems like a bug somewhere.)

- [x] `gtp-checkup`: timeout on the pkg-build server but installs correctly locally

- [x] `pict3d` (and thus `pict3d-die-cut` and `lindenmayer`): timeout on the NWU server but not the Utah server. Installs successfully locally

### Used experimental/internal/private features which changed behavior

- [x] `git-slice`: used an internal module that changed API, I've fixed it

- [x] `subtemplate`: the error file is blank on the snapshot pkg-build site, but @jsmaniac reports that this is due to mucking with the internals of `syntax-parse`. Despite fixes from @jsmaniac, the package still fails and still has a blank error file.

- [x] `debug`: The stacktrace points to something that might be expander-related

```
raco setup: error: during making for <pkgs>/debug/debug/test
raco setup:   hash-ref: no value found for key
raco setup:     key: 'bindings
raco setup:     compiling: <pkgs>/debug/debug/test/debug-repl.rkt
raco pkg install: packages installed, although setup reported errors
```

- [x] `racket-langserver`: caused by merging `template` with `syntax` and using `syntax/parse/experimental/template`. ~this might be a change in syntax-parse, or the recent change to match expanders,~ cc @lexi-lambda @rmculpepper  

```
languageId10: attribute contains non-syntax value
  value: #f
  in: languageId10
  compilation context...:
   /home/racket/build-pkgs/user/.racket/snapshot/pkgs/racket-langserver/text-document.rkt
  context...:
   raise-syntax-error
   /home/racket/build-pkgs/racket/collects/racket/match/parse-helper.rkt:169:0: match-expander-transform
```

### Bugs

- [x] `digimon`: A Typed Racket error related to changes to optional argument type checking, tracked at racket/typed-racket#721

- [x]  `phc-adt`, `phc-adt-test`, `phc-adt-doc`, `phc-adt-lib`: Appears to be a bug in the expander. Tracked in  https://github.com/jsmaniac/phc-adt/issues/18

```
raco setup: --- summary of errors ---
raco setup: error: during making for <pkgs>/phc-adt-doc/phc-adt
raco setup:   sub1: contract violation
raco setup:     expected: number?
raco setup:     given: #<startup-env>
raco setup:     compiling: <pkgs>/phc-adt-lib/phc-adt/node-low-level.hl.rkt
raco setup: error: during making for <pkgs>/phc-adt-lib/phc-adt
```

### Intentional incompatibility (to be fixed in the broken pkg)

- [x] `schema`: this appears to be related to the recent TR changes to prefabs, cc @pnwamk. This now has a PR to fix it: https://github.com/wargrey/schema/pull/1

**Comment by lexi-lambda** [comment]
> `debug`: The stacktrace points to something that might be expander-related

I think this is due to a change to `syntax-debug-info`, which is, I think, reasonable. `syntax-debug-info` makes no guarantees. The failure is only in the tests, so I think @AlexKnauth should fix the test suite.

> `racket-langserver`: this might be a change in syntax-parse, or the recent change to match expanders

The match expanders change hasn’t been merged yet, so it isn’t that.

**Comment by AlexKnauth** [comment]
The `debug-repl` feature of the `debug` uses `syntax-debug-info` to try to figure out what bindings exist in the lexical scope where it is used, so that it can put those into the repl's environment. The new expander seems to not provide this information anymore in the debug-info.

Without another way to get this information, the `debug-repl` feature will not be able to work.

**Comment by rmculpepper** [comment]
The `racket-langserver` problem should be fixed by jeapostrophe/racket-langserver#7.

**Comment by samth** [comment]
@rmculpepper If I understand correctly, this was an issue because that code was using `syntax/parse/experimental/template` already? Or because it was using `??` as a previously-unbound identifier?

**Comment by rmculpepper** [comment]
@samth yes, the former. Specifically, it was using `syntax` to generate a use of `template`.

**Comment by pnwamk** [comment]
https://github.com/wargrey/schema/pull/1 should address the Typed Racket issue with `schema`.

**Comment by jsmaniac** [comment]
`subtemplate` depends on `stxparse-info`, which patches the internals of `syntax/parse` in order to keep track of which syntax pattern variables are bound. Since syntax/parse has been mostly rewritten, I have to update the patch to work with the new code.

**Comment by samth** [comment]
@mflatt Any thoughts on the issue with `debug`?

**Comment by samth** [comment]
@jsmaniac Is this something where @rmculpepper could add something to `syntax/parse` that would make things work more sensibly?

**Comment by mflatt** [comment]
On `debug`: I'll look into making `syntax-debug-info` actually report all bindings that it can in all-bindings mode.

**Comment by jsmaniac** [comment]
@samth I had a chat about this with @rmculpepper by e-mail a few weeks ago.

For now I'll simply update my patched copy of syntax/parse and syntax/case, but if there is a good solution that everybody thinks can be merged upstream without causing havoc, I'll submit a PR.

My `subtemplate` package allows the implicit use of `generate-temporaries` in templates, using subscripts. E.g. the `tempᵢ` variable identifiers can be implicitly generated below:

```
(syntax-parse #'(a b c)
  [(vᵢ …)
   #'(let ([tempᵢ vᵢ] …)
       (displayln tempᵢ) …
       (list tempᵢ …))])
```

To do this, it needs to know that the pvar `vᵢ` is bound to relate it to the occurrence of `tempᵢ`. For that, it relies on patched versions of `syntax-case`, `syntax-parse` etc., which update a global list of bound pattern variables.

There are several issues with integrating this in the mainline:
* `with-syntax` and `syntax-case` are very low-level macros, and changing it can affect the compile time of everything else. The change can be very lightweight though (pop from a stack until the top of the stack is within scope, push back new elements).
* A query should not be able to fetch *all* bound pattern variables (for "macro security" reasons). The results could be filtered to only include those "reachable" with the same scopes as an ID passed as an argument, but I'm not sure if this is a sufficient criterion.
* @rmculpepper expressed valid concern about tracking all pattern variables, and suggested tracking only the suffixes. This would make the mechanism very ad-hoc and specific to subtemplate, though, which sounds undesirable (plus subtemplate would still need to know the "canonical" pattern variable for a given suffix).

Another way to go would be to have this bookkeeping done within the macro expander itself. The macro expander already seems to keep such information internally, as it is able to list the candidates when an ambiguous identifier was used, but there is no API to query this hidden state ([it is possible in Guile, it seems](https://stackoverflow.com/a/11032857/324969)).

**Comment by jsmaniac** [comment]
@samth subtemplate is now fixed.

**Comment by samth** [comment]
`racket-language-server` and `subtemplate` continue to fail to build as of June 9.

**Comment by jsmaniac** [comment]
@samth `subtemplate` and `stxparse-info` should now be fixed again via https://github.com/jsmaniac/stxparse-info/commit/eee50a3c56ef9c6a11e56890014cd625b2d66452 . There was another change to the internals of `racket/private/stxcase.rkt` and so on that I hadn't backported yet. Sorry for the delay.

**Comment by samth** [comment]
Closing now that v7 is out.
