### ISSUE TITLE
pkg-build failures on Racket CS

### ISSUE THREAD

**Issue by samth** [racket/racket#3457]
This issue is for tracking package build failures on Racket CS, particularly those that don't fail on Racket BC.

### pkg-build bugs
- [ ] remix https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/remix.txt (s-exp->fasl error)
- [ ] sql-sourcery https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/sql-sourcery.txt ("current-directory: `exists' access denied for /home/root/racket/")
- [ ] tessellation https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/tessellation.txt ("current-directory: `exists' access denied for /home/root/racket/")

### Uses C modules
- [ ] socketcan https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/socketcan.txt
- [ ] termios https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/termios.txt
- [ ] serial https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/serial.txt (see `termios`)

### Uses BC runtime functions
- [ ] ffi-definer-convention https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/ffi-definer-convention.txt, see https://github.com/takikawa/racket-ffi-definer-convention/issues/1
- [ ] video-v0-1 https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/video-v0-1.txt https://github.com/videolang/video/issues/66
- [x] udev https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/udev.txt (uses BC runtime functions, https://github.com/mordae/racket-udev/pull/1)
- [x] binutils https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/binutils.txt (uses BC runtime functions)

### Package bugs exposed by Racket CS thread scheduling
- [ ] ddict https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/ddict.txt (see https://github.com/pnwamk/ddict/issues/2)
- [ ] dset https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/dset.txt (see ddict)
- [ ] neuron-lib https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/neuron-lib.txt (evt testing, https://github.com/dedbox/racket-neuron/issues/21)

## Old information below.
-----------------------------------------------------------------------

Current pkg-build here: https://pkg-build.racket-lang.org
On Racket CS: https://plt.eecs.northwestern.edu/pkg-build/

#### New
- [x] hash-partition https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/hash-partition.txt (package removed)

#### HtDP testing failures
Not CS-related, see racket/htdp#121
- [x] csc-104 (they've been sent a patch)
- [x] java-lexer 
- [x] profj

#### Uses the Racket BC Runtime
- [x] ffi-definer-convention https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/ffi-definer-convention.txt, see https://github.com/takikawa/racket-ffi-definer-convention/issues/1
- [x] video-v0-1 https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/video-v0-1.txt https://github.com/videolang/video/issues/66
- [x] graphics https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/graphics.txt uses `make_sized_byte_string`, see #3494, https://github.com/wargrey/graphics/issues/3

#### Uses C Extensions

- [x] ansi https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/ansi.txt https://github.com/tonyg/racket-ansi/pull/7
- [x] unix-signals https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/unix-signals.txt https://github.com/tonyg/racket-unix-signals/pull/2
- [x] scrypt https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/scrypt.txt (maybe?)

#### Dependency on one of the above
- [x] mox see `graphics`
- [x] w3s see `graphics`
- [x] ssh-hack https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/ssh-hack.txt (see `ansi`)
- [x] terminal-phase https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/terminal-phase.txt (see `ansi`)
- [x] rmacs https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/rmacs.txt (see `ansi`)
- [x] raart https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/raart.txt (see `ansi`)

#### Racket CS Bugs
- [x] j https://plt.eecs.https://mirror.racket-lang.org/installers/7.9/racket-7.9-x86_64-linux.shnorthwestern.edu/pkg-build/server/built/fail/j.txt
- [x] neuron https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/neuron.txt
- [x] neuron-doc https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/neuron-doc.txt
- [x] remix https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/remix.txt
- [x] signature https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/signature.txt
- [x] simply-scheme https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/simply-scheme.txt

#### 3D Syntax Issue

- [x] json-sourcery https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/json-sourcery.txt https://github.com/adjkant/json-sourcery/pull/1
- [x] r-linq https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/r-linq.txt https://github.com/trajafri/r-linq/pull/1

#### Other bugs

- [x] herbie-test-deploy https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/herbie-test-deploy.txt
- [x] sci https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/sci.txt (a segfault in flomat)
- [x] semilit https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/semilit.txt
- [x] digimon https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/digimon.txt (should be fixed in the next build)
- [x] lambda-sh https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/lambda-sh.txt (see digimon)
- [x] lua https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/lua.txt (needs data/monad)

#### New

- [x] cover-test https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/cover-test.txt (timeout only on pkg-build)
- [x] fontland https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/fontland.txt (some problem with fonts and paths)
- [x] nanopass https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/nanopass.txt (timeout)
- [x] pitfall https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/pitfall.txt (see `fontland`)
- [x] quickscript-extra https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/quickscript-extra.txt (does not fail on the 8.0 release candidate)
- [x] rebellion https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rebellion.txt (timeout)
- [x] rml-core https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rml-core.txt (timeout)
- [x] punctaffy-test https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/punctaffy-test.txt (timeout, works correctly if slowly when tested)
- [x] rml-decisiontrees https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rml-decisiontrees.txt (internal timeout, used to work on 7.9, https://github.com/johnstonskj/rml-decisiontrees/pull/1)
- [x] timable https://github.com/yanyingwang/timable/issues/1

#### Probably a Racket BC bug
- [x] mock https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/mock.txt

#### Probably a Racket CS bug
- [x] quote-bad https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/quote-bad.txt (CS printer bug)
- [x] typed-struct-props https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/typed-struct-props.txt (#3536)

#### Pre-existing package issue exposed by Racket CS
- [x] dan-scheme https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/dan-scheme.txt (backtrace differences, https://github.com/david-christiansen/dan-scheme/pull/5)

#### Hash order non-determinism
- [x] net-jwt https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/net-jwt.txt (jsexpr->bytes changes results due to hash ordering, #3537)
- [x] lathe-comforts-test https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/lathe-comforts-test.txt (probably hash order nondeterminism, https://github.com/lathe/lathe-comforts-for-racket/pull/1)
- [x] polyglot-test https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/polyglot-test.txt (might be hash nondeterminism in html generation)

#### Fixed but not triaged
- [x] gmp https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/gmp.txt
- [x] turnstile-test https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/turnstile-test.txt
- [x] markdown https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/markdown.txt (timeout in random test generation)

#### Expected changes from switch to CS
- [x] anarki https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/anarki.txt (unsafe use of set-car) https://github.com/arclanguage/anarki/pull/183
- [x] rml-core https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rml-core.txt (`eq?` on doubles, test should change) https://github.com/johnstonskj/rml-core/pull/1

#### Fails in the BC 7.9 release build 
- [x] quickscript-test https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/quickscript-test.txt (fails on the release build)
- [x] sass https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/sass.txt (fails on release build)
- [x] gtp-benchmarks https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/gtp-benchmarks.txt (also fails in the release build, fixed now a test was out of date)
- [x] zeromq-r https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/zeromq-r.txt (known test problem, @rmculpepper is on it)

#### Uses unsupported features
- [x] rwind https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rwind.txt (uses BC runtime functions)
- [x] mmap https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/mmap.txt (API relies fundamentally on `make-sized-byte-string`)
- [x] rackterm https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rackterm.txt (uses BC runtime functions, easy to fix)
- [x] bazaar https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/bazaar.txt (extflonums)
- [x] describe https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/describe.txt (extflonums)
- [x] binaryio https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/binaryio.txt (single flonums)

**Comment by jackfirth** [comment]
The `mock` failure seems to be because `raise-arguments-error` accepts symbols in BC, even though that behavior isn't documented.

**Comment by rmculpepper** [comment]
`binaryio`, `gmp`, and `zeromq-r` should be fixed now.

**Comment by mflatt** [comment]
@jackfirth FWIW, for `mock`, I think the actual difference is that CS functions less reliably reports arguments other than one that fails a contract check. When `raise-arguments-error` complains about one argument but reports all the other arguments, then it happens that the error message from `raise-arguments-error` includes the intended message string — so the `check-exn` regexp check succeeds.

**Comment by samdphillips** [comment]
I was looking at `termios` and `serial` recently.  Both use C extensions just to expose system constants from header files.

**Comment by samth** [comment]
Here's a reduction of the `quote-bad` issue:

```
[samth@huor:~/tmp/quote-bad/constructor-style-print/tests (master) plt] racket
Welcome to Racket v7.9.0.3 [cs].
> (require constructor-style-print/lang/runtime-config)
> (configure #f)
> (print (list 'a 'b 'c))
(list (quote a) (quote b) (quote c))
> 
[samth@huor:~/tmp/quote-bad/constructor-style-print/tests (master) plt] racketbc
Welcome to Racket v7.9.0.3 [bc].
> (require constructor-style-print/lang/runtime-config)
> (configure #f)
> (print (list 'a 'b 'c))
(list 'a 'b 'c)
> 
```

**Comment by samth** [comment]
Here's a reduction of the `dan-scheme` issue. The following test passes on Racket BC but not on CS. It appears to be a difference in the results of `continuation-mark-set->context`:

```
#lang racket
(require rackunit
         (for-syntax syntax/parse)
         (only-in syntax/location quote-srcloc)
         (only-in setup/path-to-relative path->relative-string/library)
)
;; (check-exn/loc expr)                                                                                                                                                               
;; Tests that evaluating `expr` raises an exception                                                                                                                                   
;;  and that the exception references a function defined on the same line                                                                                                             
;;  as the `(check-exn/loc expr)` expression appears in this file.                                                                                                                    
(define-syntax (check-exn/loc stx)
  (syntax-case stx ()
    [(_ expr)
     (quasisyntax/loc stx
       (check-exn
        (lambda (e)
          (and (exn:fail? e)
            (let* ([ctx (continuation-mark-set->context (exn-continuation-marks e))]
                     [srcloc (cdar ctx)]
                     [expected-srcloc  (quote-srcloc expr)]
                     [v1 (path->relative-string/library (srcloc-source srcloc))]
                     [v2 (path->relative-string/library (srcloc-source expected-srcloc))])
                    (printf "v1: ~s\nv2: ~s\n" v1 v2)
              (and
               (string=? v1 v2)
               (printf "lines ~a ans ~a~n" (srcloc-line srcloc)
                    (srcloc-line expected-srcloc))))))
        #,(quasisyntax/loc stx (lambda () #,(syntax/loc stx expr)))
        "make sure the argument to `check-exn/loc` does not span multiple lines"))]))

(define-syntax (dan-lambda stx)
  (syntax-parse stx
    [(_ (x:id ...) body)
     (syntax/loc stx (#%plain-lambda (x ...) body))]))

(check-exn/loc (map (dan-lambda (x) (+ x x)) '(1 two 3)))
```

**Comment by samth** [comment]
`anarki` unsafely uses `unsafe-set-mcar!` on immutable pairs, which is unlikely to do the right thing on Racket CS.

**Comment by stchang** [comment]
fixed `turnstile-test` (was due to a set ordering in err msg)

**Comment by mflatt** [comment]
`rml-core` has a longer version of `(eq? 6.3 (hash-ref (hash 'key 6.3) 'key))`. I think it's just a typo.

Although `read-syntax` interns numbers, loading compiled code does not. Meanwhile, in compiled form, BC happens to preserve `eq?` within a module, while CS does not. I think changing CS is probably not worthwhile, since `eq?` is not preserved across modules.

**Comment by mflatt** [comment]
For `dan-scheme`, the issue turns out to be how much the compiler unrolls the `map`  recursion, where BC unrolls enough to inline the application of `+` to `'two`. If the list to map over is changed to `'(1 2 3 4 5 6 7 8 9 two 3)`, then the test fails in the same way for Racket BC as CS.

**Comment by mflatt** [comment]
The `ddict` failure is a known bug in the package that the test exposes more readily when run on CS.

**Comment by samth** [comment]
Here's a reduction of the `net-jwt` failure:

```
#lang racket
(require net/jwt/structs)
(define hs256-header #hasheq((alg . "HS256")))
(define hs256-ext-header  (hash-set hs256-header 'test "foo"))
(jsexpr->string64/utf-8 hs256-ext-header)
```

This prints different values on Racket 7.8 BC and HEAD Racket CS.

**Comment by samth** [comment]
The `net-jwt` failure is hash-order non-determinism manifesting in `jsexpr->bytes` non-determinism.

**Comment by samth** [comment]
We've now triaged all of these issues. I think we're at the point where none of them are bugs in Racket CS, although we may want to change the `json` library as described in #3537. 

The primary remaining failures are:
- test cases that rely implicitly on the order that hash tables are traversed
- packages that use C extensions instead of the FFI (Racket CS does not support C extensions, and the FFI should be used instead)
- packages that use the FFI to access Racket BC runtime functions that don't exist on Racket CS. 

There are a other issues that affect a few other packages, most of which have pull requests already opened to fix them.

Prior to releasing Racket CS as the default, it would be nice to get the packages that don't work fixed. The main dependencies that are relevant are by @wargrey @tonyg @BartAdv but there's a long tail of others too. If you're interested in helping to fix these, opening pull requests to fix the remaining issues is always a good idea, although check if they exist already.

**Comment by samth** [comment]
@mflatt Can you suggest a better test for what `dan-scheme` is trying to do?

**Comment by mflatt** [comment]
A test like
```
(check-exn/loc (map (if (zero? (random 1)) (dan-lambda (x) (if (= 8 (+ x x)) 'eight 'other)) 'oops) '(1 two 3)))
```
avoids inlining of the function and avoids having the erroring `+` in tail position.

**Comment by samth** [comment]
Here's a summary of the current status, intentionally pinging maintainers:

There are a bunch of packages that use various parts of the Racket BC API, or other Racket BC-specific features, that don't work on Racket CS. Some of them have pull requests to fix them:

#### With PRs:
- ansi by @tonyg 
- unix-signals by @tonyg 
- anarki by @arclanguage 

#### Without PRs:
- graphics by @wargrey 
- termios by @BartAdv 
- socketcan by @abencz
- scrypt by @tonyg 
- rwind by @Metaxal 
- mmap by @samth 
- rackterm by @willghatch 
- bazaar by @Metaxal 
- udev by @mordae 
- binutils by @lwhjp
- describe by @mbutterick (originally by Doug Williams)
- ffi-definer-convention by @takikawa 
- video-v0-1 by @LeifAndersen 

Then there are some packages whose tests or code already were non-deterministic or buggy, but fail more often or always on Racket CS.
- dan-scheme by @david-christiansen (has a PR)
- ddict and dset by @pnwamk 
- neuron-lib by @dedbox
- lathe-comforts-test by @lathe
- polyglot-test by @zyrolasting 

The remaining packages depend on some of the above, and thus don't build themselves.

If you want to help with making Racket CS a bigger success as the default variant of Racket, submitting PRs to fix some of these issues is both easy and greatly appreciated.

**Comment by mbutterick** [comment]
[fixed `describe`](https://github.com/mbutterick/describe/pull/3)

**Comment by Metaxal** [comment]
When I do `raco setup bazaar` no error is reported. Where can I get info on what needs to be fixed?
I'm using `Racket v7.9.0.9 [cs].` on Ubuntu 20.04.1, Intel i9.

**Comment by sorawee** [comment]
@Metaxal according to https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/bazaar.txt, the error is:

```
real->extfl: unsupported\n  context...:\n   /home/root/user/.local/share/racket/snapshot/pkgs/bazaar/numeric-kind.rkt:128:2: test-kind\n   .../private/for.rkt:1540:9\n   body of (submod \"/home/root/user/.local/share/racket/snapshot/pkgs/bazaar/numeric-kind.rkt\" test)\n   /home/root/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt:78:2\n   body of (submod \"/home/root/racket/share/pkgs/compiler-lib/compiler/commands/test.rkt\" process)\n   body of top-level\n
```

which occurs in `raco test`. Looks like the problem is this line? https://github.com/Metaxal/bazaar/blob/master/numeric-kind.rkt#L54

**Comment by Metaxal** [comment]
@sorawee Thank you. I've pushed a fix for this one.

@samth regarding rwind, the [failures](https://plt.eecs.northwestern.edu/pkg-build/server/built/test-fail/rwind.txt) I see are due to missing libraries, and it doesn't appear to be CS specific—or is it?
(John had told me that these libraries are not going to be installed on the test server and that the intended way to fix this is for me to embed the libraries in the package, or remove the tests. None of these options are appealing to me—both seem quite wrong at some level.)

**Comment by mflatt** [comment]
@Metaxal From the pkg-build perspective, the intended way is not to embed the libraries in the package, but to create a platform-specific dependency for the "linux-x86_64-natipkg" platform on a separate package that provides the library. See also https://pkg-build.racket-lang.org/about.html

**Comment by samth** [comment]
@Metaxal The error at that link is about `scheme_make_fd_input_port`, which is BC-specific.

**Comment by Metaxal** [comment]
@mflatt Thank you. It still seems wrong to me to have to embed foreign libs, even though it's for only natipkg—but I understand the trade-off you're facing. I'll keep it on my todo list, but that's not going to be high priority.

@samth Thanks, I didn't see that was specific to BC. Is there an existing workaround, or does it require implementing `scheme_make_fd_input_port` for CS?

**Comment by samth** [comment]
@Metaxal in general, CS doesn't provide any of the `scheme_` functions at the C level, and using the FFI to the Racket CS runtime is not usually a useful technique. Instead, you can use the functions from https://docs.racket-lang.org/foreign/Ports.html on both BC and CS now.

**Comment by Metaxal** [comment]
@samth Wonderful, thank you, I'll take a look.

**Comment by Metaxal** [comment]
rwind is fixed (via [fixing x11](https://github.com/kazzmir/x11-racket/commit/b76247de4ca307fe9021fcc25966937baa114a91)) although I must admit I'm not 100% confident the fix is 100% compliant with the previous code.

**Comment by willghatch** [comment]
On Wed, Dec 23, 2020 at 01:04:18PM -0800, Sam Tobin-Hochstadt wrote:
>- rackterm by @willghatch

It looks like I need to fix my email filtering so I notice mentions on
threads I'm already “watching”.  Rackterm is fixed now.

**Comment by zyrolasting** [comment]
@samth `polyglot-test` is fixed due to using better comparison function.

**Comment by samth** [comment]
The Northwestern pkg-build site still has some timeout issues, but we can now identify some more problems:

- `remix`, by @jeapostrophe 
- j
- json-sourcery
- hash-partition
- mic1
- sql-sourcery
- squicky
- tesselation
- typed-racket-hacks
- unb-cs3613

**Comment by mflatt** [comment]
Some of the new ones, like `mic1` and `squicky`, appear to be a difference in parallel setup and sequential setup, where parallel `raco setup` apparently considers output to stderr (shift/reduce conflicts) to mean failure.

**Comment by samth** [comment]
My guess for those ones is that it's a difference in hash ordering, and it had the same problem before. 

We should probably fix both the difference in `raco setup` and change pkg-build to run tests even if there's stderr output if possible.

**Comment by samth** [comment]
Of the new ones:
- j, mic1, squicky, typed-racket-hacks are all stderr printouts and not new failures
- remix, json-sourcery are `s-exp->fasl` errors
- sql-sourcery, tesselation are "current-directory: `exists' access denied for /home/root/racket/"
- unb-cs3613, hash-partition both attempt to contact the network

**Comment by samth** [comment]
The `remix` error doesn't re-occur on my machine. Same with `sql-sourcery`. 

The `json-sourcery` error is because the version on pkgs.racket-lang.org was pinned to a commit that doesn't have the PR I submitted; see discussion here and should be fixed now: https://github.com/adjkant/json-sourcery/pull/1

Both of `unb-cs3613` and  `hash-partition` have had the git source removed; probably @zyrolasting and David Bremner should remove them.

**Comment by samth** [comment]
Current status:

Among build failures, there are a few categories:
1. packages that have build failures due to changes at the C level between Racket BC and Racket CS. See my earlier comment about that.
2. packages that depend on category 1
3. Build failures that don't occur outside the pkg-build system (remix, tesselation, sql-sourcery)

Among test failures, there are a similar set of categories:
1. packages that use the C level BC API (udev, binutils)
2. packages with flaky tests exposed by Racket CS (neuron-lib, ddict, dset)
3. tests that timeout in the pkg-build system but not outside it (rebellion, nanopass)
4. tests that take much longer on Racket CS than Racket BC (rml-core)
5. tests that fail in pkg-build but not outside it (cover-test)
6. failures I don't understand yet (fontland, pitfall)

**Comment by samth** [comment]
In particular, there are two new genuine test failures that I see: rml-core by @johnstonskj and fontland by @mbutterick.

**Comment by mbutterick** [comment]
`pitfall`: [no failures on my CI](https://github.com/mbutterick/pitfall/actions/runs/397192208)
`fontland`: [failure only visible](https://github.com/mbutterick/fontland/actions/runs/488528529) for CS 7.9 (which I can’t reproduce locally, so can’t fix) and CS `current` (this is asking too much, I’m afraid)

**Comment by samth** [comment]
@mbutterick note that the 7.9 failures you mention look different than the "current" failures (which do reproduce locally for me if you want to try it out, but obviously that indicates some kind of regression somewhere).

**Comment by mflatt** [comment]
The `fontland` failure is a bug in `make-ctype` that I introduced fairly recently (and will fix).

**Comment by johnstonskj** [comment]
> In particular, there are two new genuine test failures that I see: rml-core by @johnstonskj and fontland by @mbutterick.

Any help required?

**Comment by samth** [comment]
@johnstonskj for some reason the `statistics.rkt` test takes forever on Racket CS (at least, on the very recent versions I've tried). If you have debugging cycles to help find the problem that's great, otherwise I'll take a look later.

**Comment by mflatt** [comment]
The issue with `statistics.rkt` in `rml-core` appears to be an interaction of futures, mutable hash tables, the lock on the hash table implemented as a semaphore, and a `box-cas!` shortcut used to implement semaphores. The `box-cas!` shortcut effectively allows a future to modify a semaphore, which in this case has the effect of taking a lock on a mutable hash table. The future gets suspended and is not touched in the test, so the hash table stays locked.

I think the solution there is to disallow the `box-cas!` shortcut when running in a future, and that way prevent the future from taking a lock.

**Comment by mflatt** [comment]
Forgot to refer to this PR in the commit: b09e10d0669a71c834530a83eaa6c870a8bcc925

**Comment by mbutterick** [comment]
One of the `fontland` test failures in CS 7.9 comes from calling into `harfbuzz` via the FFI, which makes me wonder if it’s related to an [earlier issue I had](https://www.mail-archive.com/racket-users@googlegroups.com/msg40873.html) testing `harfbuzz` on `pkg-build` (in that case the solution was to use the `natipkg` build)

**Comment by mbutterick** [comment]
It turns out the `fontland` error is nondeterministic. It seems to surface about 20% of the time on CS builds going back to at least 7.6. I can reproduce it locally, but not reliably. It arises from this [test that calls into](https://github.com/mbutterick/fontland/blob/957be9fe375a431621282a4c739e71d4e025b44c/fontland/unsafe/harfbuzz.rkt#L164) `harfbuzz` via FFI. The test is supposed to return the byte string `#"en"` (representing a two-letter language code) but occasionally returns a longer string like `#"en3"` or `#"enft"`. I don't know what kind of pointer corruption would cause that behavior. But I tend to think the bug isn’t in my code (this test has never failed on BC).

**Comment by mflatt** [comment]
For `harfbuzz`, I think you want `(define _bstring _bytes/nul-terminated)`. With just `_bytes`, the byte string passed to `hb_language_from_string` is not NUL-terminated, except maybe (often) accidentally.

**Comment by mbutterick** [comment]
Thanks, I wouldn’t have noticed that. I’ve made that change and all the CS tests for `fontland` now pass on multiple trials.

**Comment by samth** [comment]
Another couple test failure issues:
- punctaffy-test
- rml-decisiontrees

**Comment by samth** [comment]
`rml-decisiontrees` turns out to be a regression on Racket BC as well. Error message:

```
with-limit: out of time                                                     
  context...:                                                               
   /home/samth/sw/plt/extra-pkgs/sandbox-lib/racket/sandbox.rkt:412:0: call-with-limits
   /home/samth/sw/plt/extra-pkgs/sandbox-lib/racket/sandbox.rkt:716:0: evaluate-program
   /home/samth/sw/plt/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/samth/sw/plt/extra-pkgs/sandbox-lib/racket/sandbox.rkt:857:5                                                                                   
   /home/samth/sw/plt/extra-pkgs/sandbox-lib/racket/sandbox.rkt:853:2: user-process
```

However, the error only appears when running multiple files, ie with `raco test -p rml-decisiontrees`. I have not found a combination of command line arguments to trigger the failure for a single file.

**Comment by samth** [comment]
The `rml-decisiontrees` failure only happens when the `rml-decisiontrees/test/main.rkt` file is compiled to `.zo` form.

**Comment by samth** [comment]
Well, 8.0 is out, and the situation has continued to improve. Thanks to @tonyg for fixing his packages. I've re-organized the description to focus on the remaining 13 packages with problems.

**Comment by countvajhula** [comment]
I've been seeing the "`exists` access denied" failure on the package archive for a new package I'm working on, and I think I've isolated the change that causes the failure. Please see [this comment](https://github.com/countvajhula/ionic/issues/6#issuecomment-846614585) for details. It seems to be caused by importing the `math` library in a sandbox interpreter for building scribble docs, but I'll be doing some additional testing to confirm.

**Comment by countvajhula** [comment]
Confirmed. Adding this require:
```
(only-in math sqr)
```
is a reliable way to reproduce the error:
```
current-directory: `exists' access denied for /home/root/racket/
```
And removing it causes the error to go away.

I looked at some of the other repos in the issue description and they don't feature the same require. But this is a reliable way to reproduce the error in my repo, on [this branch](https://github.com/countvajhula/ionic/commits/debug-pkg-build-error) that I created specially for this purpose.

Please let me know if I can help further in getting to the bottom of this.

@samth

**Comment by countvajhula** [comment]
Here FTR is the stack trace when the package `ionic` was failing (I've removed the `math` require to avoid the issue, for now):

```
raco setup: running: <pkgs>/ionic/scribblings/ionic.scrbl
current-directory: `exists' access denied for /home/root/racket/
  context...:
   /home/root/racket/collects/racket/private/config.rkt:30:4: exe-relative-path->complete-path
   /home/root/racket/collects/setup/private/dirs.rkt:22:2: get-config-table
   /home/root/racket/collects/racket/promise.rkt:65:10
   /home/root/racket/collects/racket/promise.rkt:45:2
   /home/root/racket/collects/setup/dirs.rkt:190:2: host-lib-search-dirs
   /home/root/racket/collects/racket/promise.rkt:65:10
   /home/root/racket/collects/racket/promise.rkt:45:2
   /home/root/racket/collects/racket/private/so-search.rkt:28:0: so-find
   /home/root/racket/collects/racket/runtime-path.rkt:84:9
   .../private/map.rkt:40:19: loop
   body of "/home/root/racket/share/pkgs/math-lib/math/private/bigfloat/gmp.rkt"
   body of top-level
   /home/root/racket/share/pkgs/sandbox-lib/racket/sandbox.rkt:725:9: ns
   /home/root/racket/share/pkgs/sandbox-lib/racket/sandbox.rkt:739:18

```

I noticed that the other two packages in the issue description (sql-sourcery and tessellation) fail on the same step:
`   /home/root/racket/collects/racket/private/config.rkt:30:4: exe-relative-path->complete-path`

For two out of the three packages, it happens via sandbox.rkt, while for the other it's via lazy-require.rkt, but they ultimately fail on this step in config.rkt.

[This commit on that file](https://github.com/racket/racket/commit/3d3f1a408c6e56a4d702ebad70bbf362042ae370) sounds like it may be related. Could it be that lazy-require and sandbox execution cause the path to reflect differently the way that commit message talks about? Just hazarding wild guesses on the off chance it sparks something for someone familiar.
