### ISSUE TITLE
Support Viewing Documents Through the Browser on Chromebook

### ISSUE THREAD

**Issue by shhyou** [racket/racket#3995]
As reported in #3893, documentation on Chromebook is currently not fully functioning. The main issue is that ChromeOS runs Linux applications in a virtual machine, so only `$HOME` is shared between the host OS and the Linux apps. In the current setup, `net/sendurl` opens a URL via a temporary file to support cross-platform URL redirection. However, the temporary file is not visible in the host OS and therefore failed to open.

A workaround is to install a second browser in the virtual machine. Nevertheless, opening the documentation through the host OS is more convenient. This PR is aimed at supporting such a feature. Even if the goal cannot be accomplished, there should be some documentation.

## Functionality of User-scope Documentation

- Documentation
    - [ ] Browse installation-scope package from index
    - [x] Browse user-scope package from index (already working without any PR)
    - [ ] Search the local database
    - [ ] Visit the License page and the Acknowledgements page
    - [ ] Reference installation-scope tags from user-scope packages
        - Before this PR: redicrected through `local-redirect` from the online documentation
        - After this PR:
- `raco doc`
    - [x] Launch the index (already working without any PR)
    - [ ] Search (`raco doc <keyword>`)
- `,doc` of XREPL
    - [x] Launch the index (already working without any PR)
    - [x] Visit a definition (`,doc <a-binding>`) (By A and B)
- DrRacket
    - [x] Launch the index (already working without any PR)
    - [ ] Search (Search Helpdesk)
    - [x] Visit a definition (View Documentation) (By A and B)

## Implementations

1. [ ] A. Allow `net/sendurl` to send URLs directly (#3993).
2. [ ] B. Allow the user to config whether to use trampolines or not (racket/drracket#511).
3. [ ] C. Fix the hard-coded URLs generated by `racket-index` (#3996) and `scribble-lib` (racket/scribble#315).
4. [ ] D. Add an option in `raco setup` to trigger the configurations in 3.
5. [ ] (E). Detect the platform and suggest/choose an appropriate configuration. Not sure if this is a good idea.
